In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import tensorflow as tf
import warnings
warnings.filterwarnings("ignore")


In [3]:
tf.executing_eagerly() 
#https://medium.com/coding-blocks/eager-execution-in-tensorflow-a-more-pythonic-way-of-building-models-e461810618c8

True

In [4]:
import tensorflow as tf

In [5]:
  text = open("shakespeare.txt",'r').read()

In [6]:
vocab = sorted(set(text)) # set is for distinct elements

In [7]:
vocab

['\n',
 ' ',
 '!',
 '"',
 '&',
 "'",
 '(',
 ')',
 ',',
 '-',
 '.',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 ':',
 ';',
 '<',
 '>',
 '?',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z',
 '[',
 ']',
 '_',
 '`',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z',
 '|',
 '}']

In [8]:
len(vocab)

84

In [9]:
for pair in enumerate(vocab):
    print(pair)

(0, '\n')
(1, ' ')
(2, '!')
(3, '"')
(4, '&')
(5, "'")
(6, '(')
(7, ')')
(8, ',')
(9, '-')
(10, '.')
(11, '0')
(12, '1')
(13, '2')
(14, '3')
(15, '4')
(16, '5')
(17, '6')
(18, '7')
(19, '8')
(20, '9')
(21, ':')
(22, ';')
(23, '<')
(24, '>')
(25, '?')
(26, 'A')
(27, 'B')
(28, 'C')
(29, 'D')
(30, 'E')
(31, 'F')
(32, 'G')
(33, 'H')
(34, 'I')
(35, 'J')
(36, 'K')
(37, 'L')
(38, 'M')
(39, 'N')
(40, 'O')
(41, 'P')
(42, 'Q')
(43, 'R')
(44, 'S')
(45, 'T')
(46, 'U')
(47, 'V')
(48, 'W')
(49, 'X')
(50, 'Y')
(51, 'Z')
(52, '[')
(53, ']')
(54, '_')
(55, '`')
(56, 'a')
(57, 'b')
(58, 'c')
(59, 'd')
(60, 'e')
(61, 'f')
(62, 'g')
(63, 'h')
(64, 'i')
(65, 'j')
(66, 'k')
(67, 'l')
(68, 'm')
(69, 'n')
(70, 'o')
(71, 'p')
(72, 'q')
(73, 'r')
(74, 's')
(75, 't')
(76, 'u')
(77, 'v')
(78, 'w')
(79, 'x')
(80, 'y')
(81, 'z')
(82, '|')
(83, '}')


In [10]:
# can't slice a list of tuples so convert them into dictionary

In [11]:
char_to_ind = {char:ind for ind,char in enumerate(vocab)}
#char:ind- this is the way we want the ouput to be
# ind,char in enumerate coz that's how the tuples in the vocabs are..integer and dn character

In [12]:
char_to_ind

{'\n': 0,
 ' ': 1,
 '!': 2,
 '"': 3,
 '&': 4,
 "'": 5,
 '(': 6,
 ')': 7,
 ',': 8,
 '-': 9,
 '.': 10,
 '0': 11,
 '1': 12,
 '2': 13,
 '3': 14,
 '4': 15,
 '5': 16,
 '6': 17,
 '7': 18,
 '8': 19,
 '9': 20,
 ':': 21,
 ';': 22,
 '<': 23,
 '>': 24,
 '?': 25,
 'A': 26,
 'B': 27,
 'C': 28,
 'D': 29,
 'E': 30,
 'F': 31,
 'G': 32,
 'H': 33,
 'I': 34,
 'J': 35,
 'K': 36,
 'L': 37,
 'M': 38,
 'N': 39,
 'O': 40,
 'P': 41,
 'Q': 42,
 'R': 43,
 'S': 44,
 'T': 45,
 'U': 46,
 'V': 47,
 'W': 48,
 'X': 49,
 'Y': 50,
 'Z': 51,
 '[': 52,
 ']': 53,
 '_': 54,
 '`': 55,
 'a': 56,
 'b': 57,
 'c': 58,
 'd': 59,
 'e': 60,
 'f': 61,
 'g': 62,
 'h': 63,
 'i': 64,
 'j': 65,
 'k': 66,
 'l': 67,
 'm': 68,
 'n': 69,
 'o': 70,
 'p': 71,
 'q': 72,
 'r': 73,
 's': 74,
 't': 75,
 'u': 76,
 'v': 77,
 'w': 78,
 'x': 79,
 'y': 80,
 'z': 81,
 '|': 82,
 '}': 83}

In [13]:
char_to_ind['H']

33

In [14]:
ind_to_char = np.array(vocab)


In [15]:
ind_to_char

array(['\n', ' ', '!', '"', '&', "'", '(', ')', ',', '-', '.', '0', '1',
       '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '<', '>', '?',
       'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
       'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z',
       '[', ']', '_', '`', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i',
       'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v',
       'w', 'x', 'y', 'z', '|', '}'], dtype='<U1')

In [16]:
ind_to_char[33]

'H'

In [17]:
encoded_text = np.array([char_to_ind[c] for c in text]) # the entire text 

In [18]:
encoded_text

array([ 0,  1,  1, ..., 30, 39, 29])

In [19]:
encoded_text.shape

(5445609,)

In [20]:
sample = text[:500]
sample

"\n                     1\n  From fairest creatures we desire increase,\n  That thereby beauty's rose might never die,\n  But as the riper should by time decease,\n  His tender heir might bear his memory:\n  But thou contracted to thine own bright eyes,\n  Feed'st thy light's flame with self-substantial fuel,\n  Making a famine where abundance lies,\n  Thy self thy foe, to thy sweet self too cruel:\n  Thou that art now the world's fresh ornament,\n  And only herald to the gaudy spring,\n  Within thine own bu"

In [21]:
encoded_text[:500]

array([ 0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1, 12,  0,  1,  1, 31, 73, 70, 68,  1, 61, 56, 64,
       73, 60, 74, 75,  1, 58, 73, 60, 56, 75, 76, 73, 60, 74,  1, 78, 60,
        1, 59, 60, 74, 64, 73, 60,  1, 64, 69, 58, 73, 60, 56, 74, 60,  8,
        0,  1,  1, 45, 63, 56, 75,  1, 75, 63, 60, 73, 60, 57, 80,  1, 57,
       60, 56, 76, 75, 80,  5, 74,  1, 73, 70, 74, 60,  1, 68, 64, 62, 63,
       75,  1, 69, 60, 77, 60, 73,  1, 59, 64, 60,  8,  0,  1,  1, 27, 76,
       75,  1, 56, 74,  1, 75, 63, 60,  1, 73, 64, 71, 60, 73,  1, 74, 63,
       70, 76, 67, 59,  1, 57, 80,  1, 75, 64, 68, 60,  1, 59, 60, 58, 60,
       56, 74, 60,  8,  0,  1,  1, 33, 64, 74,  1, 75, 60, 69, 59, 60, 73,
        1, 63, 60, 64, 73,  1, 68, 64, 62, 63, 75,  1, 57, 60, 56, 73,  1,
       63, 64, 74,  1, 68, 60, 68, 70, 73, 80, 21,  0,  1,  1, 27, 76, 75,
        1, 75, 63, 70, 76,  1, 58, 70, 69, 75, 73, 56, 58, 75, 60, 59,  1,
       75, 70,  1, 75, 63

In [22]:
print(text[:500])


                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bu


In [23]:
line = "From fairest creatures we desire increase"

In [24]:
len(line)

41

In [25]:
# our training sequence must be long enough in order to pick up the general structure of the text

In [26]:
lines = '''
From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
'''
#triple quotes coz  it is multi line

In [27]:
len(lines)

133

In [28]:
seq_len =120

In [29]:
total_num_seq = len(text)//(seq_len+1) # coz of zero indexing
#// divides and drops reminder

In [30]:
total_num_seq

45005

In [31]:
#https://www.geeksforgeeks.org/tensorflow-tf-data-dataset-from_tensor_slices/
char_dataset =tf.data.Dataset.from_tensor_slices(encoded_text) 
#https://www.tensorflow.org/api_docs/python/tf/data/Dataset
char_dataset

<TensorSliceDataset shapes: (), types: tf.int64>

In [32]:
sequences = char_dataset.batch(seq_len+1,drop_remainder=True)
#when we take input text/target text, we have to take([:-1])/([1:]) which should be equal to 120 i.e the length of sequences,
#this can be achieved by taking seq_len + 1 in batches.
#if we take only seq_len, dn input/target_text will have length of 119.


In [33]:
def create_seq_targets(seq):
    input_txt = seq[:-1] #hello I am Prita
    target_txt = seq[1:] #ello I am Pritam
    
    return input_txt,target_txt

In [34]:
dataset = sequences.map(create_seq_targets) #MAPS the function of create_seq_targets to sequences
dataset.take(1)

<TakeDataset shapes: ((120,), (120,)), types: (tf.int64, tf.int64)>

In [35]:
for input_txt,target_txt in dataset.take(1):# first sequence
    print(input_txt.numpy())
    print(" ".join(ind_to_char[input_txt.numpy()]))  #joins all the characters and  adds space between the chars
    print('\n')
    print(target_txt.numpy())
    print("".join(ind_to_char[target_txt.numpy()]))
    # the last para has a extra white space
    # here dataset.take(1) will always return the first sequence because the data is not shuffled 

[ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0
  1  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74
  1 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45
 63 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74
 60  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75]

                                           1 
     F r o m   f a i r e s t   c r e a t u r e s   w e   d e s i r e   i n c r e a s e , 
     T h a t   t h e r e b y   b e a u t y ' s   r o s e   m i g h t   n e v e r   d i e , 
     B u t


[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0  1
  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74  1
 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45 63
 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74 60
  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75  1]
                     1
  F

In [36]:
input_txt

<tf.Tensor: shape=(120,), dtype=int64, numpy=
array([ 0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1, 12,  0,  1,  1, 31, 73, 70, 68,  1, 61, 56, 64,
       73, 60, 74, 75,  1, 58, 73, 60, 56, 75, 76, 73, 60, 74,  1, 78, 60,
        1, 59, 60, 74, 64, 73, 60,  1, 64, 69, 58, 73, 60, 56, 74, 60,  8,
        0,  1,  1, 45, 63, 56, 75,  1, 75, 63, 60, 73, 60, 57, 80,  1, 57,
       60, 56, 76, 75, 80,  5, 74,  1, 73, 70, 74, 60,  1, 68, 64, 62, 63,
       75,  1, 69, 60, 77, 60, 73,  1, 59, 64, 60,  8,  0,  1,  1, 27, 76,
       75])>

In [37]:
batch_size = 128


In [38]:
buffer_size = 10000 # we shuffle in batches coz if we shuffle the entire data set , we might end up commiting error
dataset = dataset.shuffle(buffer_size).batch(batch_size,drop_remainder=True)
#It is very important that dataset is shuffled well to avoid any element of bias/patterns 
#take 10k of those elements and shuffle them

In [39]:
dataset
#input sequence 128,120 ;-> 128 sequence with 120 characters long
#target sequence 128,120

<BatchDataset shapes: ((128, 120), (128, 120)), types: (tf.int64, tf.int64)>

In [64]:
dataset.take(1)

<TakeDataset shapes: ((128, 120), (128, 120)), types: (tf.int64, tf.int64)>

In [65]:
vocab_size = len(vocab)
vocab_size

84

In [66]:
embed_dim = 64 #should be around the same size as vocab, something we can play around with
#this is for our embedding layer
#embedding turns positive integers into dense vectors

In [67]:
rnn_neurons = 1026

In [68]:
from tensorflow.keras.losses import sparse_categorical_crossentropy

In [69]:
#since we are one hot encoded, we need from_logits to be true, hence we define it

In [70]:
def sparse_cat_loss(y_true,y_pred):
    return sparse_categorical_crossentropy(y_true,y_pred,from_logits=True,)

In [71]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,GRU,Dense

In [72]:
#None means it is a dynamic shape. It can take any value depending on the batch size you choose.
def create_model(vocab_size,embed_dim,rnn_neurons,batch_size):
    model = Sequential()
    model.add(Embedding(vocab_size,embed_dim,batch_input_shape = [batch_size,None]))
    model.add(GRU(rnn_neurons,return_sequences=True,stateful=True,recurrent_initializer='glorot_uniform'))
    model.add(Dense(vocab_size))
    model.compile('adam',loss = sparse_cat_loss)


    
    return model

In [73]:
model = create_model(vocab_size=vocab_size,embed_dim=embed_dim,rnn_neurons=rnn_neurons,batch_size=batch_size)

In [74]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (128, None, 64)           5376      
_________________________________________________________________
gru_1 (GRU)                  (128, None, 1026)         3361176   
_________________________________________________________________
dense_1 (Dense)              (128, None, 84)           86268     
Total params: 3,452,820
Trainable params: 3,452,820
Non-trainable params: 0
_________________________________________________________________


In [75]:
for input_example_batch, target_example_batch in dataset.take(3):
  print(input_example_batch)
  
  # from here till (model. fit) we are just checking  to ensure that everyting is fine
  #dataset.take(3) will take 3 random samples from the dataset
  #each time the cell is run, we will get different input_example_batch
  #this is because our dataset now has been shuffled.#dataset = dataset.shuffle(buffer_size).batch(batch_size,drop_remainder=True) 


tf.Tensor(
[[60 10  0 ...  1  5 57]
 [75 70  1 ... 26 76 61]
 [ 1 57 60 ... 63 60 73]
 ...
 [ 8  1 63 ...  0  1  1]
 [59  1 73 ... 75 63 80]
 [60 67 67 ...  1 63 60]], shape=(128, 120), dtype=int64)
tf.Tensor(
[[60  1 64 ... 71 67 60]
 [ 1  1  1 ... 56 77 60]
 [73 60 69 ... 10  0  1]
 ...
 [73 75  1 ... 70 61  1]
 [56 69 70 ... 63  8  1]
 [40 37 26 ... 60  1 74]], shape=(128, 120), dtype=int64)
tf.Tensor(
[[68 60  1 ... 66 60  1]
 [75 56 64 ... 68 80  1]
 [60 66 74 ... 67 56 75]
 ...
 [56 69 64 ... 59 25  1]
 [64 68  1 ... 75  1 52]
 [ 0  1  1 ...  1 57 76]], shape=(128, 120), dtype=int64)


In [76]:
for input_example_batch, target_example_batch in dataset.take(1):
  example_batch_predictions = model(input_example_batch)

In [77]:
 example_batch_predictions[0]

<tf.Tensor: shape=(120, 84), dtype=float32, numpy=
array([[ 0.0056132 , -0.00504818, -0.00134756, ..., -0.00218874,
         0.00048715, -0.00061802],
       [ 0.00366667, -0.00505131,  0.00339404, ...,  0.00018865,
         0.00199569, -0.00685113],
       [ 0.00445918, -0.00572371,  0.00384926, ..., -0.00289748,
         0.00588458, -0.00534065],
       ...,
       [-0.00202772, -0.00207145, -0.00556949, ..., -0.00127369,
        -0.00310731,  0.00567011],
       [ 0.0047515 , -0.00695132, -0.00409351, ..., -0.00198909,
        -0.00106151,  0.00205109],
       [ 0.00323016, -0.00104503, -0.00051489, ...,  0.00716028,
        -0.00155583, -0.00031859]], dtype=float32)>

In [78]:
  example_batch_predictions.shape

TensorShape([128, 120, 84])

In [79]:
sample_indices = tf.random.categorical(example_batch_predictions[0],num_samples=1)


In [80]:
sample_indices

<tf.Tensor: shape=(120, 1), dtype=int64, numpy=
array([[ 8],
       [72],
       [ 6],
       [33],
       [74],
       [55],
       [64],
       [20],
       [14],
       [42],
       [27],
       [66],
       [39],
       [40],
       [35],
       [53],
       [59],
       [71],
       [41],
       [75],
       [32],
       [31],
       [26],
       [66],
       [73],
       [17],
       [71],
       [ 7],
       [72],
       [11],
       [76],
       [56],
       [33],
       [18],
       [48],
       [37],
       [ 0],
       [32],
       [ 5],
       [51],
       [23],
       [ 4],
       [30],
       [20],
       [23],
       [11],
       [ 6],
       [23],
       [39],
       [53],
       [49],
       [26],
       [54],
       [50],
       [14],
       [83],
       [39],
       [53],
       [41],
       [60],
       [29],
       [ 7],
       [13],
       [82],
       [27],
       [71],
       [81],
       [80],
       [44],
       [45],
       [32],
       [74],
       [59],
   

In [81]:
ind_to_char[sample_indices]# hence we perform tf.squeeze to reduce the sample indices by one dimension 

array([[','],
       ['q'],
       ['('],
       ['H'],
       ['s'],
       ['`'],
       ['i'],
       ['9'],
       ['3'],
       ['Q'],
       ['B'],
       ['k'],
       ['N'],
       ['O'],
       ['J'],
       [']'],
       ['d'],
       ['p'],
       ['P'],
       ['t'],
       ['G'],
       ['F'],
       ['A'],
       ['k'],
       ['r'],
       ['6'],
       ['p'],
       [')'],
       ['q'],
       ['0'],
       ['u'],
       ['a'],
       ['H'],
       ['7'],
       ['W'],
       ['L'],
       ['\n'],
       ['G'],
       ["'"],
       ['Z'],
       ['<'],
       ['&'],
       ['E'],
       ['9'],
       ['<'],
       ['0'],
       ['('],
       ['<'],
       ['N'],
       [']'],
       ['X'],
       ['A'],
       ['_'],
       ['Y'],
       ['3'],
       ['}'],
       ['N'],
       [']'],
       ['P'],
       ['e'],
       ['D'],
       [')'],
       ['2'],
       ['|'],
       ['B'],
       ['p'],
       ['z'],
       ['y'],
       ['S'],
       ['T'],
       ['G'],
     

In [82]:
sample_indices = tf.squeeze(sample_indices,axis = -1).numpy() #changes the dimension from (120,1) to (120,)

In [83]:
sample_indices

array([ 8, 72,  6, 33, 74, 55, 64, 20, 14, 42, 27, 66, 39, 40, 35, 53, 59,
       71, 41, 75, 32, 31, 26, 66, 73, 17, 71,  7, 72, 11, 76, 56, 33, 18,
       48, 37,  0, 32,  5, 51, 23,  4, 30, 20, 23, 11,  6, 23, 39, 53, 49,
       26, 54, 50, 14, 83, 39, 53, 41, 60, 29,  7, 13, 82, 27, 71, 81, 80,
       44, 45, 32, 74, 59, 52, 44, 32, 49, 45, 49, 56, 76, 77,  5, 46, 59,
       80,  9, 32, 30, 54, 27, 80, 59, 71, 64, 66, 74, 43, 70, 37, 16, 44,
       42, 11, 75, 52,  2, 23, 21, 29, 52,  4, 58, 27,  1, 50, 13, 60,  2,
       17])

In [84]:
sample_indices.shape

(120,)

In [85]:
ind_to_char[sample_indices]

array([',', 'q', '(', 'H', 's', '`', 'i', '9', '3', 'Q', 'B', 'k', 'N',
       'O', 'J', ']', 'd', 'p', 'P', 't', 'G', 'F', 'A', 'k', 'r', '6',
       'p', ')', 'q', '0', 'u', 'a', 'H', '7', 'W', 'L', '\n', 'G', "'",
       'Z', '<', '&', 'E', '9', '<', '0', '(', '<', 'N', ']', 'X', 'A',
       '_', 'Y', '3', '}', 'N', ']', 'P', 'e', 'D', ')', '2', '|', 'B',
       'p', 'z', 'y', 'S', 'T', 'G', 's', 'd', '[', 'S', 'G', 'X', 'T',
       'X', 'a', 'u', 'v', "'", 'U', 'd', 'y', '-', 'G', 'E', '_', 'B',
       'y', 'd', 'p', 'i', 'k', 's', 'R', 'o', 'L', '5', 'S', 'Q', '0',
       't', '[', '!', '<', ':', 'D', '[', '&', 'c', 'B', ' ', 'Y', '2',
       'e', '!', '6'], dtype='<U1')

In [86]:
epochs = 30

In [87]:
model.fit(dataset,epochs=epochs)

Epoch 1/30
351/351 [==============================] - 54s 147ms/step - loss: 3.1763
Epoch 2/30
351/351 [==============================] - 53s 149ms/step - loss: 1.8778
Epoch 3/30
351/351 [==============================] - 54s 152ms/step - loss: 1.5457
Epoch 4/30
351/351 [==============================] - 54s 150ms/step - loss: 1.3866
Epoch 5/30
351/351 [==============================] - 55s 154ms/step - loss: 1.3091
Epoch 6/30
351/351 [==============================] - 54s 152ms/step - loss: 1.2610
Epoch 7/30
351/351 [==============================] - 55s 155ms/step - loss: 1.2249
Epoch 8/30
351/351 [==============================] - 55s 155ms/step - loss: 1.1990
Epoch 9/30
351/351 [==============================] - 55s 153ms/step - loss: 1.1765
Epoch 10/30
351/351 [==============================] - 55s 154ms/step - loss: 1.1584
Epoch 11/30
351/351 [==============================] - 54s 151ms/step - loss: 1.1424
Epoch 12/30
351/351 [==============================] - 55s 154ms/step - lo

In [92]:
model.save('shakespeare.h5')

In [93]:


model = create_model(vocab_size,embed_dim,rnn_neurons,batch_size = 1)

model.load_weights('shakespeare.h5')

model.build(tf.TensorShape([1,None]))

In [94]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (1, None, 64)             5376      
_________________________________________________________________
gru_2 (GRU)                  (1, None, 1026)           3361176   
_________________________________________________________________
dense_2 (Dense)              (1, None, 84)             86268     
Total params: 3,452,820
Trainable params: 3,452,820
Non-trainable params: 0
_________________________________________________________________


In [95]:
def generate_text(model,start_seed,gen_size = 500, temp =1.0):

  num_generate  = gen_size

  input_eval = [char_to_ind[s] for s in start_seed]

  input_eval = tf.expand_dims(input_eval,0)

  text_generated = []

  temperature = temp

  model.reset_states()

  for i in range(num_generate):

    predictions = model(input_eval)

    predictions = tf.squeeze(predictions,0)

    predicted_id = tf.random.categorical(predictions, num_samples=1)[-1,0].numpy()

    input_eval = tf.expand_dims([predicted_id], 0)

    text_generated.append(ind_to_char[predicted_id])

  return (start_seed + ''.join(text_generated))

In [96]:
generate_text(model,"Julius",gen_size = 500,temp = 1.0)

"Julius,\n    For they are not half-joy of late.\n    Go, my young lady ride, went to thee\n    Who on my sorrow may receive it,\n    If their better issue shrouds set down\n    And take us het his beards! Please you too\n    young men'ned. There's a good soldier, to ride thee now in Grother,\n  And ask no tree, which, stoppedorking in,\n    And, so did, by this, good women. Lucherous love,\n    Taken I quoted.\n  HORTENSIO. Not thee about thy hand! ANTUR't send her two bones\n     told of beauty, lads like men, "